highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: qinwang-git.github.io
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Qin Wang's Resume
name: Qin Wang
email: qinwang@swin.edu.au
email_full: qinwang@swin.edu.au
website: 
website_full: 
github: qinwang-git
twitter: twitter
linkedin: https://www.linkedin.com/in/randy-wang/
address:
  city: Melbourne
  country: Australia
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
